# Source: cluster-api-aws/templates/aws-cluster.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: 67ef5a63-ce17-4b16-a007-fae06766677a
  namespace: 67ef5a63-ce17-4b16-a007-fae06766677a
spec:
  region: ap-northeast-2
  sshKeyName: tks-seoul
  bastion:
    enabled: true
    instanceType: t3.micro
    disableIngressRules: false
    allowedCIDRBlocks:
      - 127.0.0.1/32
